global:
  imageRegistry:
  imagePullSecrets: []
  storageClass:
  redis:
    password: redis123
kubeVersion:
nameOverride:
fullnameOverride:
commonLabels: {}
commonAnnotations: {}
clusterDomain: cluster.local
extraDeploy: []
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 6.2.4-debian-10-r0
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
architecture: replication
auth:
  enabled: true
  sentinel: true
  password: ""
  existingSecret:
  existingSecretPasswordKey:
  usePasswordFiles: false
commonConfiguration: |-
  appendonly yes
  save ""
existingConfigmap:
master:
  configuration:
  disableCommands:
    - FLUSHDB
    - FLUSHALL
  command: []
  args: []
  preExecCmds: []
  extraFlags: []
  extraEnvVars: []
  extraEnvVarsCM:
  extraEnvVarsSecret:
  containerPort: 9736
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  customLivenessProbe: {}
  customReadinessProbe: {}
  resources:
    limits: {}
    requests: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  schedulerName:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  priorityClassName: ""
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  shareProcessNamespace: false
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  spreadConstraints: {}
  lifecycleHooks: {}
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: {}
  initContainers: {}
  persistence:
    enabled: true
    path: /data
    subPath: ""
    storageClass:
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    selector: {}
    existingClaim:
  service:
    type: ClusterIP
    port: 9736
    nodePort:
    externalTrafficPolicy: Cluster
    clusterIP:
    loadBalancerIP:
    loadBalancerSourceRanges: []
    annotations: {}
  terminationGracePeriodSeconds: 30
replica:
  replicaCount: 3
  configuration:
  disableCommands:
    - FLUSHDB
    - FLUSHALL
  command: []
  args: []
  preExecCmds: []
  extraFlags: []
  extraEnvVars: []
  extraEnvVarsCM:
  extraEnvVarsSecret:
  containerPort: 9736
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  customLivenessProbe: {}
  customReadinessProbe: {}
  resources:
    limits: {}
    requests: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  schedulerName:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  priorityClassName: ""
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  shareProcessNamespace: false
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  spreadConstraints: {}
  lifecycleHooks: {}
  extraVolumes: []
  extraVolumeMounts: []
  sidecars: {}
  initContainers: {}
  persistence:
    enabled: true
    path: /data
    subPath: ""
    storageClass:
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}
    selector: {}
  service:
    type: ClusterIP
    port: 9736
    nodePort:
    externalTrafficPolicy: Cluster
    clusterIP:
    loadBalancerIP:
    loadBalancerSourceRanges: []
    annotations: {}
  terminationGracePeriodSeconds: 30
sentinel:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/redis-sentinel
    tag: 6.2.3-debian-10-r25
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
  masterSet: sentinelmaster
  quorum: 2
  downAfterMilliseconds: 60000
  failoverTimeout: 18000
  cleanDelaySeconds: 5
  parallelSyncs: 1
  staticID: false
  configuration:
  command: []
  args: []
  preExecCmds: []
  containerPort: 29736
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  customLivenessProbe: {}
  customReadinessProbe: {}
  resources:
    limits: {}
    requests: {}
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  lifecycleHooks: {}
  extraVolumes: []
  extraVolumeMounts: []
  service:
    type: ClusterIP
    port: 9736
    sentinelPort: 29736
    nodePorts:
      redis:
      sentinel:
    externalTrafficPolicy: Cluster
    clusterIP:
    loadBalancerIP:
    loadBalancerSourceRanges: []
    annotations: {}
  terminationGracePeriodSeconds: 30
networkPolicy:
  enabled: false
  allowExternal: true
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
podSecurityPolicy:
  create: false
  enabled: false
rbac:
  create: false
  rules: []
serviceAccount:
  create: true
  name: ""
  annotations: {}
pdb:
  create: false
  minAvailable: 1
  maxUnavailable:
tls:
  enabled: false
  authClients: true
  certificatesSecret:
  certFilename:
  certKeyFilename:
  certCAFilename:
  dhParamsFilename:
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.23.1-debian-10-r24
    pullPolicy: IfNotPresent
    pullSecrets: []
  redisTargetHost: "localhost"
  extraArgs: {}
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  resources:
    limits: {}
    requests: {}
  podLabels: {}
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
  service:
    type: ClusterIP
    port: 9121
    externalTrafficPolicy: Cluster
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}
  sentinel:
    enabled: false
    image:
      registry: docker.io
      repository: bitnami/redis-sentinel-exporter
      tag: 1.7.1-debian-10-r153
      pullPolicy: IfNotPresent
      pullSecrets: []
    extraArgs: {}
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
    resources:
      limits: {}
      requests: {}
    service:
      type: ClusterIP
      port: 9355
      externalTrafficPolicy: Cluster
      loadBalancerIP: ""
      loadBalancerSourceRanges: []
      annotations: {}
  serviceMonitor:
    enabled: false
    namespace:
    interval: 30s
    scrapeTimeout:
    relabellings: []
    honorLabels: false
    additionalLabels: {}
  prometheusRule:
    enabled: false
    namespace:
    additionalLabels: {}
    rules: []
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r97
    pullPolicy: Always
    pullSecrets: []
  resources:
    limits: {}
    requests: {}
  containerSecurityContext:
    runAsUser: 0
sysctl:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r97
    pullPolicy: Always
    pullSecrets: []
  command: []
  mountHostSys: false
  resources:
    limits: {}
    requests: {}
